### ISSUE TITLE
Export all examinations works only once

### ISSUE THREAD

**Issue by jeyjey626** [jeyjey626/neuropathy-app#58] opened 2023-06-18 13:49 UTC
From settings screen

**Comment by jeyjey626** [comment] 2023-06-20 11:21
Scenario 1:
1. Go to settings
2. Click export all
3. do not save, back to app
4. Try to export again (does not work)

Scenario 2:
3. Save, back to app
4. Try to export again (does not work)


Try also on singular exam exports

**Comment by s174508** [comment] 2023-06-25 12:54
Can't reproduce on either emulator or android. Attempted both export all and export single exam

**Comment by jeyjey626** [comment] 2023-06-25 14:25
> Can't reproduce on either emulator or android. Attempted both export all and export single exam

Did you try on debug or release versions?

**Comment by jeyjey626** [comment] 2023-06-25 14:37
Both debug and release v did not repro on master. @s174508 if that is true for you as well, please close this issue

**Comment by s174508** [comment] 2023-06-26 11:27
Did debug on emulator and release on phone. Closing

**Closed by s174508** 2023-06-26 11:27 UTC
Labels: bug
